### ISSUE TITLE
INK_GetStrokeP not defined

### ISSUE THREAD

**Issue by akforrest** [phatware/WritePadSDK#1]
In the API (includes and docs), there is a function defined as

```
int INK_GetStrokeP( INK_DATA_PTR pData, int nStroke, CGStroke * ppoints, int * pnWidth, COLORREF * pColor );
```

The windows dll provided (x86 or 64) does not export this symbol.

**Comment by phatware** [comment]
Fixed in WritePad SDK 5.5
